#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBaseDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Dados")]
	public partial class BD_DadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDado(Dado instance);
    partial void UpdateDado(Dado instance);
    partial void DeleteDado(Dado instance);
    partial void InsertLanzamiento(Lanzamiento instance);
    partial void UpdateLanzamiento(Lanzamiento instance);
    partial void DeleteLanzamiento(Lanzamiento instance);
    partial void InsertTipoDado(TipoDado instance);
    partial void UpdateTipoDado(TipoDado instance);
    partial void DeleteTipoDado(TipoDado instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public BD_DadosDataContext() : 
				base(global::ConexionBaseDatos.Properties.Settings.Default.BD_DadosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BD_DadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_DadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_DadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_DadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dado> Dado
		{
			get
			{
				return this.GetTable<Dado>();
			}
		}
		
		public System.Data.Linq.Table<Lanzamiento> Lanzamiento
		{
			get
			{
				return this.GetTable<Lanzamiento>();
			}
		}
		
		public System.Data.Linq.Table<TipoDado> TipoDado
		{
			get
			{
				return this.GetTable<TipoDado>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dado")]
	public partial class Dado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _numeroCaras;
		
		private System.Nullable<int> _caraObtenida;
		
		private System.Nullable<int> _lanzamientoId;
		
		private System.Nullable<int> _tipoDadoId;
		
		private EntityRef<Lanzamiento> _Lanzamiento;
		
		private EntityRef<TipoDado> _TipoDado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnnumeroCarasChanging(System.Nullable<int> value);
    partial void OnnumeroCarasChanged();
    partial void OncaraObtenidaChanging(System.Nullable<int> value);
    partial void OncaraObtenidaChanged();
    partial void OnlanzamientoIdChanging(System.Nullable<int> value);
    partial void OnlanzamientoIdChanged();
    partial void OntipoDadoIdChanging(System.Nullable<int> value);
    partial void OntipoDadoIdChanged();
    #endregion
		
		public Dado()
		{
			this._Lanzamiento = default(EntityRef<Lanzamiento>);
			this._TipoDado = default(EntityRef<TipoDado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroCaras", DbType="Int")]
		public System.Nullable<int> numeroCaras
		{
			get
			{
				return this._numeroCaras;
			}
			set
			{
				if ((this._numeroCaras != value))
				{
					this.OnnumeroCarasChanging(value);
					this.SendPropertyChanging();
					this._numeroCaras = value;
					this.SendPropertyChanged("numeroCaras");
					this.OnnumeroCarasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caraObtenida", DbType="Int")]
		public System.Nullable<int> caraObtenida
		{
			get
			{
				return this._caraObtenida;
			}
			set
			{
				if ((this._caraObtenida != value))
				{
					this.OncaraObtenidaChanging(value);
					this.SendPropertyChanging();
					this._caraObtenida = value;
					this.SendPropertyChanged("caraObtenida");
					this.OncaraObtenidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanzamientoId", DbType="Int")]
		public System.Nullable<int> lanzamientoId
		{
			get
			{
				return this._lanzamientoId;
			}
			set
			{
				if ((this._lanzamientoId != value))
				{
					if (this._Lanzamiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlanzamientoIdChanging(value);
					this.SendPropertyChanging();
					this._lanzamientoId = value;
					this.SendPropertyChanged("lanzamientoId");
					this.OnlanzamientoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoDadoId", DbType="Int")]
		public System.Nullable<int> tipoDadoId
		{
			get
			{
				return this._tipoDadoId;
			}
			set
			{
				if ((this._tipoDadoId != value))
				{
					if (this._TipoDado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipoDadoIdChanging(value);
					this.SendPropertyChanging();
					this._tipoDadoId = value;
					this.SendPropertyChanged("tipoDadoId");
					this.OntipoDadoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lanzamiento_Dado", Storage="_Lanzamiento", ThisKey="lanzamientoId", OtherKey="id", IsForeignKey=true)]
		public Lanzamiento Lanzamiento
		{
			get
			{
				return this._Lanzamiento.Entity;
			}
			set
			{
				Lanzamiento previousValue = this._Lanzamiento.Entity;
				if (((previousValue != value) 
							|| (this._Lanzamiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lanzamiento.Entity = null;
						previousValue.Dado.Remove(this);
					}
					this._Lanzamiento.Entity = value;
					if ((value != null))
					{
						value.Dado.Add(this);
						this._lanzamientoId = value.id;
					}
					else
					{
						this._lanzamientoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lanzamiento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoDado_Dado", Storage="_TipoDado", ThisKey="tipoDadoId", OtherKey="id", IsForeignKey=true)]
		public TipoDado TipoDado
		{
			get
			{
				return this._TipoDado.Entity;
			}
			set
			{
				TipoDado previousValue = this._TipoDado.Entity;
				if (((previousValue != value) 
							|| (this._TipoDado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoDado.Entity = null;
						previousValue.Dado.Remove(this);
					}
					this._TipoDado.Entity = value;
					if ((value != null))
					{
						value.Dado.Add(this);
						this._tipoDadoId = value.id;
					}
					else
					{
						this._tipoDadoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TipoDado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lanzamiento")]
	public partial class Lanzamiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _fechaLanzamiento;
		
		private System.Nullable<int> _usuarioId;
		
		private EntitySet<Dado> _Dado;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfechaLanzamientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaLanzamientoChanged();
    partial void OnusuarioIdChanging(System.Nullable<int> value);
    partial void OnusuarioIdChanged();
    #endregion
		
		public Lanzamiento()
		{
			this._Dado = new EntitySet<Dado>(new Action<Dado>(this.attach_Dado), new Action<Dado>(this.detach_Dado));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaLanzamiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaLanzamiento
		{
			get
			{
				return this._fechaLanzamiento;
			}
			set
			{
				if ((this._fechaLanzamiento != value))
				{
					this.OnfechaLanzamientoChanging(value);
					this.SendPropertyChanging();
					this._fechaLanzamiento = value;
					this.SendPropertyChanged("fechaLanzamiento");
					this.OnfechaLanzamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioId", DbType="Int")]
		public System.Nullable<int> usuarioId
		{
			get
			{
				return this._usuarioId;
			}
			set
			{
				if ((this._usuarioId != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioIdChanging(value);
					this.SendPropertyChanging();
					this._usuarioId = value;
					this.SendPropertyChanged("usuarioId");
					this.OnusuarioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lanzamiento_Dado", Storage="_Dado", ThisKey="id", OtherKey="lanzamientoId")]
		public EntitySet<Dado> Dado
		{
			get
			{
				return this._Dado;
			}
			set
			{
				this._Dado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Lanzamiento", Storage="_Usuario", ThisKey="usuarioId", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Lanzamiento.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Lanzamiento.Add(this);
						this._usuarioId = value.id;
					}
					else
					{
						this._usuarioId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dado(Dado entity)
		{
			this.SendPropertyChanging();
			entity.Lanzamiento = this;
		}
		
		private void detach_Dado(Dado entity)
		{
			this.SendPropertyChanging();
			entity.Lanzamiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoDado")]
	public partial class TipoDado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private EntitySet<Dado> _Dado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public TipoDado()
		{
			this._Dado = new EntitySet<Dado>(new Action<Dado>(this.attach_Dado), new Action<Dado>(this.detach_Dado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoDado_Dado", Storage="_Dado", ThisKey="id", OtherKey="tipoDadoId")]
		public EntitySet<Dado> Dado
		{
			get
			{
				return this._Dado;
			}
			set
			{
				this._Dado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dado(Dado entity)
		{
			this.SendPropertyChanging();
			entity.TipoDado = this;
		}
		
		private void detach_Dado(Dado entity)
		{
			this.SendPropertyChanging();
			entity.TipoDado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _puntaje;
		
		private EntitySet<Lanzamiento> _Lanzamiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnpuntajeChanging(System.Nullable<int> value);
    partial void OnpuntajeChanged();
    #endregion
		
		public Usuario()
		{
			this._Lanzamiento = new EntitySet<Lanzamiento>(new Action<Lanzamiento>(this.attach_Lanzamiento), new Action<Lanzamiento>(this.detach_Lanzamiento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntaje", DbType="Int")]
		public System.Nullable<int> puntaje
		{
			get
			{
				return this._puntaje;
			}
			set
			{
				if ((this._puntaje != value))
				{
					this.OnpuntajeChanging(value);
					this.SendPropertyChanging();
					this._puntaje = value;
					this.SendPropertyChanged("puntaje");
					this.OnpuntajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Lanzamiento", Storage="_Lanzamiento", ThisKey="id", OtherKey="usuarioId")]
		public EntitySet<Lanzamiento> Lanzamiento
		{
			get
			{
				return this._Lanzamiento;
			}
			set
			{
				this._Lanzamiento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lanzamiento(Lanzamiento entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Lanzamiento(Lanzamiento entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
}
#pragma warning restore 1591
